version: "3.8"

services:
  nginx:
    image: lab1-nginx
    container_name: nginx
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./static:/var/www/static
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    networks:
      - nginx_network
    restart: unless-stopped

networks:
  nginx_network:
